edition = "2021"
# condense_wildcard_suffixes = true
# comment_width = 100
# wrap_comments = true
# enum_discrim_align_threshold = 20
# format_strings = true
newline_style = "Unix"
# overflow_delimited_expr = true
# reorder_impl_items = true
# struct_field_align_threshold = 10
use_small_heuristics = "Default"
